name: Hello World!

on:
  push:
    branches:
      - setup-github-actions

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello World!"

      - name: Run Date
        run: date

      - name: open file
        run: ls
